### ISSUE TITLE
Empty Module Description causes Layout overlay

### ISSUE THREAD

**Issue by TomasKostadinov** [rolandtoth/AdminOnSteroids#1]
![nodesc](https://cloud.githubusercontent.com/assets/11008743/18027971/3210516e-6c72-11e6-8645-10fcefd28928.png)

"my nice custom module" causes a layout overlay because there is no description given.

**Comment by rolandtoth** [comment]
I have fixed this, will be available in the next version (054). 

Thanks!

**Comment by TomasKostadinov** [comment]
@rolandtoth Thank you for making this awesome module!

**Comment by rolandtoth** [comment]
Thanks! 

You can try the new version now. And congrats for the the #1 here :)

**Comment by TomasKostadinov** [comment]
@rolandtoth 
After Updating I got: 
```
Parse Error: syntax error, unexpected '.', expecting ',' or ';' (line 23 of /home/annsint/public_html_dev/site/modules/AdminOnSteroids/AdminOnSteroids.module) 

This error message was shown because: site is in debug mode. ($config->debug = true; => /site/config.php). Error has been logged.
```
Which has been added in the latest commit (49e4fe34fb181911119ef5d76fd66c39688d67ed).
https://github.com/rolandtoth/AdminOnSteroids/blame/master/AdminOnSteroids.module#L23

**Comment by rolandtoth** [comment]
Thanks, this is most likely a PHP version issue, will fix soon.

**Comment by TomasKostadinov** [comment]
@rolandtoth I already fixed it :)

**Comment by rolandtoth** [comment]
Thanks! I hope v055 doesn't contain such surprises :)

**Comment by TomasKostadinov** [comment]
@rolandtoth You're welcome!

**Comment by rolandtoth** [comment]
Amen :)
