### ISSUE TITLE
Template Edit Links showing in Pagelist for non Super User

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#10]
When visiting /admin/page/ non SuperUsers can see the template edit links in a tooltip.

Here is a screenshot:
![pages processwire pw3 dev 2016-09-28 17-14-15](https://cloud.githubusercontent.com/assets/40570/18934426/43054e20-859f-11e6-9ae8-5540eaa58604.jpg)

In this picture the user matt only has the role blogger which only has these permissions:
![edit page bloggers pw3 dev 2016-09-28 17-17-18](https://cloud.githubusercontent.com/assets/40570/18934467/7c719916-859f-11e6-9274-bb5b640fb957.jpg)

Hope that helps

**Comment by rolandtoth** [comment]
Thanks, fixed in v070.

**Comment by gmclelland** [comment]
That fixed it.  Thank you
