### ISSUE TITLE
Error after upgrading PW (latest dev version) and PHP to 7.3.1

### ISSUE THREAD

**Issue by tiefenb** [rolandtoth/AdminOnSteroids#104]
Hi, I switched to PHP 7.3.1, PW >3.0.125 and Session in Redis (session.save_path = redis) and now I'm getting this error from AdminOnSteroids:

```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/site/modules/AdminOnSteroids/AdminOnSteroids.module on line 2621

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/site/modules/AdminOnSteroids/AdminOnSteroids.module:2621) in /var/www/html/wire/core/Session.php on line 1083

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/site/modules/AdminOnSteroids/AdminOnSteroids.module:2621) in /var/www/html/wire/core/Session.php on line 1084
```

PHP: 7.3.1
Processwire: latest dev version (>3.0.125)

**Comment by tiefenb** [comment]
After removing the "continue" on line 2621 in AdminOnSteroids.module, my site works again:

<img width="558" alt="bildschirmfoto 2019-02-06 um 08 57 05" src="https://user-images.githubusercontent.com/488163/52327665-32561100-29ed-11e9-97b9-6d1107dcb58d.png">

**Comment by tiefenb** [comment]
Oh, I thought I was on the latest but was on v2.0.7.
Error is now fixed after upgrading.

**Comment by rolandtoth** [comment]
Thanks!
