### ISSUE TITLE
RestrictTreeDropdown option can result in empty dropdown

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#105]
I use the RestrictTreeDropdown option on all my sites, but have just noticed that if a role does not have any of the following...

* Page Add shortcut for any templates
* page-edit-recent permission
* page-lister permission

...then an empty dropdown under Pages occurs:

![2019-02-15_152147](https://user-images.githubusercontent.com/1538852/52830388-75269000-3135-11e9-86b8-75287cfd54b8.png)

### Possible fix

```js
if (RestrictTreeDropdownSettings === true) {

    $('a[href$="/page/list/"]').parent('li').each(function() {
        if(!$(this).siblings().length) $(this).parent().css('visibility', 'hidden');
        $(this).remove();
    });
    $('a[href$="/page/"]').children('i.quicklink-open').remove(); // Reno

}
```

So if there are no other sibling `li`s then the parent `ul` is hidden. The `ul` can't be removed from the DOM unfortunately because then jQueryUI packs a sad.

**Comment by rolandtoth** [comment]
Thanks, finally I could also see it (there was one submenu item that was always shown whch was a custom AOS NavItem). I haven't used your code but this CSS:

```css
html.aos ul.pw-dropdown-menu.prnav:empty {
    display: none !important;
}
```

**Comment by Toutouwai** [comment]
Thanks!
