### ISSUE TITLE
Trash confirmation option causes wrong form layout

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#106]
There is an option in the Misc category: _Move empty trash confirmation checkbox above trash items_

Perhaps due to core updates to the Trash form, this option is now putting the confirm checkbox at the _bottom_ of the form, below the buttons. Perhaps this option is no longer needed now that the confirm checkbox seems to be at the top by default?

Without AOS:
![2019-02-21_175833](https://user-images.githubusercontent.com/1538852/53144744-5e36e080-3602-11e9-9c3a-d43a4f5a1f60.png)

With AOS trash checkbox option enabled:
![2019-02-21_175845](https://user-images.githubusercontent.com/1538852/53144769-76a6fb00-3602-11e9-8834-674341b5b0e3.png)

**Comment by rolandtoth** [comment]
Thanks, it's been removed in v2.0.13.
