### ISSUE TITLE
Page tree doesn't load when changing a page's parent

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#11]
When I edit a page and try to change the parent, the page tree doesn't load.  All I see is the page id in the input field.  If I disable AOS, it works fine.

I'm running the latest AOS and PW 3.035

**Comment by rolandtoth** [comment]
Thanks, nice catch! No idea how I haven't come across with this.

For a quick fix change this line
https://github.com/rolandtoth/AdminOnSteroids/blob/master/AdminOnSteroids.js#L429

to this:
`$('.Inputfield:not(.InputfieldPageListSelect)').on('reloaded', function () {`

**Comment by gmclelland** [comment]
Yep, that worked.  Thank you
