### ISSUE TITLE
AdminOnSteroids and PHP 7.4 (Beta 1)

### ISSUE THREAD

**Issue by tiefenb** [rolandtoth/AdminOnSteroids#111]
I just testet my PW and AdminOnSteroids with PHP 7.4 Beta 1 and got this Error:

Deprecated: Unparenthesized a ? b : c ? d : e is deprecated. Use either (a ? b : c) ? d : e or a ? b : (c ? d : e) in /var/www/html/site/modules/AdminOnSteroids/AdminOnSteroids.module on line 1886

**Comment by rolandtoth** [comment]
Thanks, I' added the fix though I couldn't try as I wasn't able to add PHP 7.4 to my Laragon. But it works on earlier versions as before.

**Comment by tiefenb** [comment]
thx works now
