### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#112]
Small typo I noticed.

![Module: AdminOnSteroids • mansfieldtexasarts test 2019-09-06 09-50-49](https://user-images.githubusercontent.com/40570/64437441-e86d0080-d08b-11e9-9e34-8288c6f6ca6b.jpg)

Should be alt + s

**Comment by rolandtoth** [comment]
Thanks, it's been fixed in v2.0.20
