### ISSUE TITLE
Asset paths check gives wrong result

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#114]
The "Check" button in the asset paths section seems to be giving a "success" result for files that do not exist at this path.

![2020-01-29_124024](https://user-images.githubusercontent.com/1538852/73315280-8ad48d00-4294-11ea-940b-b4d497e2f0a9.png)

This is on Windows if that's relevant. AOS v2.0.20

**Comment by Toutouwai** [comment]
Sorry, false alarm.

This issue occurred on a nearly-clean PW installation but it had previously been used to demonstrate an issue with Tracy Debugger + AJAX + SessionHandlerDB. Even though the relevant modules and templates were deleted there was still some odd behaviour persisting. When I tested on a new clean installation there was no problem.

**Comment by rolandtoth** [comment]
Happy to hear 👍
