### ISSUE TITLE
Does not work with php 7.4

### ISSUE THREAD

**Issue by saschanos** [rolandtoth/AdminOnSteroids#117]
shows several php errors

**Comment by adrianbj** [comment]
@saschanos - it would be good to know what errors you are seeing. I have been running on PHP 7.4 for quite some time and haven't noticed any errors, so it likely comes down to what enhancements you have enabled. I am sure it would help @rolandtoth if you could detail each error you are seeing :)

**Comment by saschanos** [comment]
Used an older version; 2.0.20 works fine. Thank you!
