### ISSUE TITLE
CkEditor modal dialogs broken with 4.14.0

### ISSUE THREAD

**Issue by adrianbj** [rolandtoth/AdminOnSteroids#118]
Hey @rolandtoth - since PW upgraded the version of CkEditor to 4.14.0 it's no longer possible to interact with Ckeditor's dialogs, such as View Source, Table, etc.

The culprit is: `.cke_dialog_background_cover{z-index:103000 !important}` in aos.min.css 

There are some other similar rules just after that one which don't seem to be a problem in my limited testing, but maybe they can all be removed or modified so they don't break things?

Thanks!

**Comment by Sebiworld** [comment]
I had to delete the rule manually from the module's styles/aos.min.css file, since I needed the source-view to work. Until now, there seem to be no negative effects without the rule...

**Comment by adrianbj** [comment]
> because I needed the source-view to work

Remember that this doesn't just affect view source - it also breaks the image insert dialog.

@rolandtoth - I'd submit a PR to fix this, but I honestly don't really understand why any of those `cke_*` `z-index` rules are there. Can they all be removed?

**Comment by rolandtoth** [comment]
@adrianbj 

I made those z-indexes that high because I thought that's the best way to make sure the cke overlay covers the admin header, sidebar, etc. So far it was OK, apparently recent ckeditor updates broke this workaround.

I would say if removing the rule you mentioned in the first comment works then it's enough for now, until it proves the opposite :)

**Comment by rolandtoth** [comment]
Just updated to 2.0.21, please check. I could reproduce the source dialog issue but the image insert dialog was OK here.

**Comment by tbba** [comment]
I can confirm that its fixed here - thank you!!

**Comment by adrianbj** [comment]
Yep, all good again now - thanks @rolandtoth
