### ISSUE TITLE
InputfieldURLChecker - preview internal links

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#12]
## Request
Is there any way you could add the ability to preview links that are internal in URL fields? like /about-this-page ?

## Problem
I'm using https://github.com/marcostoll/processwire-fieldtype-assisted-url which allows you to select pages from the tree.  It inserts links like /about-this-page into the URL field, but the InputfieldURLChecker module won't preview it because right now it only previews external links.

**Comment by rolandtoth** [comment]
Try v076, there's a support in it for FieldtypeAssistedURL. There are some minor updates to IUC, eg. you can use the middle mouse button to open the URL in a new browser tab (useful if the default setting is open in modal). Panel support was removed because it caused more trouble than good.

**Comment by gmclelland** [comment]
Thank you for adding the support for relative URLs.  I like how the module list is two column instead of three.  It makes it easier to scan.

IUC works fine after selecting pages in the modal dialog provided by the FieldtypeAssistedURL module, but I noticed IUC doesn't seem to engage after the link is inserted into the FieldtypeAssistedURL URL field until you hit the tab key.  At first I didn't think it was working until I hit the tab key in the URL field.

I also noticed if you select another page it remembers the previously inputted url until the tab key re-engages it.  That also happens in URL field itself, not within the modal.

I hope I explained it well enough.

I'm not sure, but maybe these problems are because I'm using a slightly modified version of FieldtypeAssistedURL?  I'm using the master version with the Pull Request 
at https://github.com/marcostoll/processwire-fieldtype-assisted-url/pull/4

I would also suggest hiding the IUC arrow icon in the input field until it receives a value.  No point in showing a disabled icon.

Hope that helps

**Comment by rolandtoth** [comment]
I'm not getting the TAB key weirdness using the "stock" FieldtypeAssistedURL (Chrome, Firefox latest versions). If you could give it a go to see are these happening there that would be great. If they are present, a detailed report would be fine on how to reproduce.

In the first vesions of IUC the icon was hidden but that was confusing because if the button was on the left side you couldn't click in the beginning of the input. Otherwise I like that you can tell instantly that the field is IUC powered by the icon. I agree that in case of FieldtypeAssistedURL there are too many icons though.

**Comment by gmclelland** [comment]
I also just tried testing with an older version of FieldtypeAssistedURL Jul 30, 2015 and noticed the same problem in Chrome and Firefox on a mac.

## Steps to reproduce

1. Click the Link button on the URL field provided by FieldtypeAssistedURL.  The modal shows.  Start typing the name of a page.  Select the page.  Click "Choose URL".  The page's url is inserted into the input of the url field.
2. Immediately try clicking on the IUC arrow.  It doesn't do anything.
3. Now hit the Tab key and try clicking the IUC arrow.  IUC will now show the page in a new browser tab.

**Comment by rolandtoth** [comment]
My bad. Just realized I haven't know about FAU's main usage. I always used it by clicking on the "Link" toolbar button in CKEditor.

I've uploaded a fix, and there's also a CSS fix for FAU, making it full-width.

**Comment by gmclelland** [comment]
Thank you.  That fixed the problem.

I think the new CSS changes need to be removed though.  There is similar CSS fixes for FAU now in the latest commit of the master branch.  https://github.com/marcostoll/processwire-fieldtype-assisted-url/commit/7080b88e499b67f4ead58420a17ece363a79c0c6

**Comment by rolandtoth** [comment]
Thanks! I'll leave the CSS in place until the new version is released. Otherwise the IUC icon is not inside the input field and looks differently as elsewhere.

**Comment by gmclelland** [comment]
Having the CSS in doesn't appear to hurt anything.  I'll try to let you know once FAU makes a new release.
