### ISSUE TITLE
Array to string conversion in addIUCLink()

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#13]
I get an array to string conversion notice:

> PHP Notice: Array to string conversion in ...\modules\AdminOnSteroids\AdminOnSteroids.module:1372

Dumping variable $url I get:

> in ...\modules\AdminOnSteroids\AdminOnSteroids.module:1372 array (1)
> 0 => 0

AOS v0.8.1

**Comment by rolandtoth** [comment]
Is there anything special in your URL field that causes this issue? 
Is it in a repeater, or is it FieldtypeAssistedURL or does it have a textformatter applied?

At first I do not see anything that would result in an array for the field value.

**Comment by Toutouwai** [comment]
There is no URL field in the template of the page being edited. There is a URL field in the template of a PageTable field on the page but I don't think that's triggering the notice.

There is a Page Autocomplete field in the template and that seems to be the cause: if I comment out [line 601](https://github.com/rolandtoth/AdminOnSteroids/blob/master/AdminOnSteroids.module#L601) I don't get the notice. I'm not really clear on why the URL checker would need to hook InputfieldPageAutocomplete::render().

**Comment by rolandtoth** [comment]
That's because the support for FieldtypeAssistedURL. I'll check how this can be improved, thanks for the info.

**Comment by rolandtoth** [comment]
Just pushed a fix to this, no errors here aftewards (v082). Thanks for the report!

**Comment by Toutouwai** [comment]
Great, thanks!
