### ISSUE TITLE
Filter box on modules pages

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#14]
What do you think about adding a filter box to admin/module/?

Someone can just start typing the name of the module and it would filter the results.

Similar to https://github.com/rolandtoth/AdminOnSteroids#filefieldtweaks filter box.

**Comment by rolandtoth** [comment]
I see the advantages but I'm not sure about it. There's the Search in the header that you can also use, and using ctrl+F is also only a few keystrokes more. Additionally the module list is grouped into tabs so I guess it's not that straightforward to filter them.

**Comment by gmclelland** [comment]
It's in Drupal 8.  You see how it works at https://simplytest.me/project/drupal/8.x-2.1

After going through the installer, go to /admin/modules to see it in action.

> Additionally the module list is grouped into tabs so I guess it's not that straightforward to filter them.
Hmm.. Maybe a filter box on each tab??

**Comment by rolandtoth** [comment]
Done in v087.

**Comment by gmclelland** [comment]
Looks and works great!
