### ISSUE TITLE
Add hotkey to focus the search input

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#15]
What do you think about adding a hotkey to focus the search input while in the admin?

I come from a Drupal background where I'm used to using Alt+d which triggers the https://www.drupal.org/project/coffee module to search.

**Comment by rolandtoth** [comment]
Done in v085 (works on alt+d and double ctrl).

**Comment by gmclelland** [comment]
Great!  Thank you
