### ISSUE TITLE
Filter box when editing roles and viewing admin/access/permissions/

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#16]
It might also be helpful to add the filter boxes to the permissions when editing a role like admin/access/roles/edit/?id=38 and viewing the permissions list at admin/access/permissions/

**Comment by gmclelland** [comment]
Works perfectly!  Thank you

**Comment by rolandtoth** [comment]
Thanks - I expect some issues here and there with this general filter box but I think it's a good start.
