### ISSUE TITLE
Syntax Error on upgrade

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#17]
Thought you might want to know...I just updated to the latest AOS and got this message.

![parse error syntax error unexpected 2016-10-27 07-56-29](https://cloud.githubusercontent.com/assets/40570/19767962/ecfa31b6-9c1a-11e6-936a-72b8fdd34794.jpg)

**Comment by rolandtoth** [comment]
Sorry, this doesn't work on PHP < 7. Just uploaded v0.9.2 with a fix.

**Comment by gmclelland** [comment]
That worked.  Thanks for the quick turn release.
