### ISSUE TITLE
The "X" isn't vertically centered

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#18]
Minor issue...I noticed the "x" isn't vertically centered inside the input.

![edit page home pw3 dev 2016-10-27 08-26-04](https://cloud.githubusercontent.com/assets/40570/19768996/494c3bae-9c1f-11e6-813a-550bad592d61.jpg)

Hope that helps.  Love the new filters by the way.

**Comment by gmclelland** [comment]
Removing the top property seems to fix it.

![edit page home pw3 dev 2016-10-27 08-29-24](https://cloud.githubusercontent.com/assets/40570/19769064/8dc3b03c-9c1f-11e6-963b-73a7ee2776ed.jpg)

**Comment by rolandtoth** [comment]
Thanks, will be corrected in the next update. It's OK in Reno theme but I forgot about the Default.

**Comment by rolandtoth** [comment]
It should now in v0.9.3.

**Comment by gmclelland** [comment]
Yes, it does.  Thanks again.
