### ISSUE TITLE
InputfieldURLChecker overlaps button fieldtype-assisted-url button

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#19]
On a default installation the fieldtype-assisted-url button is on the left and InputfieldURLChecker is also on the left which shows an overlap.

Can you change the default InputfieldURLChecker button position to be on the right side of the field?

**Comment by rolandtoth** [comment]
Thanks for the info. Your suggestion would only partially solve the issue. I have corrected the CSS which will be included in the next update.

**Comment by rolandtoth** [comment]
Should be now fixed in v094.
