### ISSUE TITLE
Disabled Do not distribute modules into tabs causes display issues

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#20]
If I disable "Do not distribute modules into tabs" I can no longer see the tabs at admin/modules using the default theme.

![modules processwire pw3 dev 2016-10-31 11-39-33](https://cloud.githubusercontent.com/assets/40570/19862520/b77c26b0-9f5e-11e6-8df3-9815f37580a3.jpg)

**Comment by rolandtoth** [comment]
You mean the module tabs like site, configure etc? That's the point of this setting, use only one big table with all the modules, without tabs.

**Comment by gmclelland** [comment]
Yes, those tabs.  If the setting "Do not distribute modules into tabs" is disabled(unchecked) it should show all tabs like normal, but it doesn't.

If I enable the setting "Do not distribute modules into tabs" the tabs disappear as expected.

**Comment by rolandtoth** [comment]
I see now - the moduleFilter overlaps with the WireTabs. It's fixed in the latest commit https://github.com/rolandtoth/AdminOnSteroids/commit/c995c128ac412cff0b5af43f2f11c9cb022b9dcc.

**Comment by gmclelland** [comment]
That fixed it.
