### ISSUE TITLE
Edit modules in modal on long click

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#23]
I'm not sure this is working for me in the default theme.  Nothing happens when I long click on the module name on /admin/module/ using Chrome.

![modules processwire pw3 dev 2016-11-08 11-13-39](https://cloud.githubusercontent.com/assets/40570/20109175/81a34590-a5a4-11e6-8da2-a0f9f101ac51.jpg)

Just thought I would let you know.

**Comment by adrianbj** [comment]
Same problem here!

**Comment by rolandtoth** [comment]
I think it's a Chrome issue. Works for me in FF. Longclick does not work on main pagelist in Chrome when AOS is uninstalled.

**Comment by gmclelland** [comment]
Long click works for me on the page actions in the page tree on /admin/page/ in Chrome.  Long clicking the Edit link opens the edit page in a modal.

**Comment by adrianbj** [comment]
>Long click works for me on the page actions in the page tree on /admin/page/ in Chrome. Long clicking the Edit link opens the edit page in a modal.

Me too :)

**Comment by rolandtoth** [comment]
AOS only adds the required classes there. Perhaps PW binds the event sooner so AOS doesn't have a chance. I use SlimJet (Chromium-based) and long-click only occassionally works for me, I'll check in "real" Chrome too, but as I wrote perhaps it's a timing issue I'm not sure how to fix.

**Comment by gmclelland** [comment]
For what it is worth, I'm pretty sure it was working in the past.

**Comment by rolandtoth** [comment]
Just tried with Chrome 44 and then with the latest Chrome (54), and everything's fine. I guess you use the latest AOS so that couldn't be the issue.

Just to make sure, do you have these classes on the module name link?

`pw-modal pw-modal-large pw-modal-longclick`

**Comment by adrianbj** [comment]
> Just to make sure, do you have these classes on the module name link?

Yep:
```
<a href="edit?name=AdminOnSteroids" class="pw-modal pw-modal-large pw-modal-longclick" data-autoclose="#Inputfield_submit_save_module.needsReload, #Inputfield_submit_save_module_forceClose, #Inputfield_submit_save_module_forceCloseRefresh" data-buttons="#Inputfield_submit_save_module, #Inputfield_submit_save_module_forceClose, #Inputfield_submit_save_module_forceCloseRefresh"><span class="ConfigurableModule"><i class="fa fa-fw fa-medkit"></i> AdminOnSteroids</span></a>
```

**Comment by gmclelland** [comment]
I think the modules page is missing the jquery.longclick.min.js 
![pages processwire pw3 dev 2016-11-08 14-26-55](https://cloud.githubusercontent.com/assets/40570/20115852/7d1427e0-a5bf-11e6-9870-f2aabd66cef9.jpg)

**Comment by rolandtoth** [comment]
It's loaded according to the Network tab, are you sure it's missing there?

**Comment by gmclelland** [comment]
I don't see it listed under Sources or Network tab.  I couldn't find where it is loaded in AdminOnSteriods.module either.

**Comment by gmclelland** [comment]
In AdminOnSteroids.module I added:
`            if (in_array('moduleModal', $configData[$subModule])) {
                $this->modules->get('JqueryCore')->use('longclick');
            }`

and it worked.  I can make a pull request if you want?

**Comment by rolandtoth** [comment]
AOS doesn't load this JS, it's only adding CSS classes so PW can add the longclick events.

Thanks for the code - I'm actually just added the same but it's good to know it's working then. I'll add an extra check to load it only on the modules page.

**Comment by rolandtoth** [comment]
This should be fixed now in the latest version, could you confirm that?

**Comment by gmclelland** [comment]
It works now
