### ISSUE TITLE
Save dropdown problems in PW 3.0.41

### ISSUE THREAD

**Issue by MichaelvanLaar** [rolandtoth/AdminOnSteroids#24]
Since upgrading to PW 3.0.41 the save buttons and dropdowns don’t look and work as expected when AOS is enabled.

Even with the option “Misc -> Show save dropdown on hover instead on click” disabled the dropdown of the save button at the bottom of the page opens when hovering over the arrow section of the button. The arrow section of the save button at the top of the page is not visible at all and thus no dropdown available here.

![screenshot-save-dropdown](https://cloud.githubusercontent.com/assets/311043/20492872/c64ccb68-b016-11e6-9a23-3da83573fe87.png)

**Comment by MichaelvanLaar** [comment]
Solution: Disabling and re-enabling the module after upgrading to PW 3.0.41 solved the problem in three different installations. Strange, but it seems to work.

**Comment by rolandtoth** [comment]
Glad you figured it out. Sometimes I also face this issue when I rename or move features to another submodule. I think I should add this info to the readme.
