### ISSUE TITLE
change Code Mirror theme

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#25]
Hi Tpr,

I was having trouble figuring out how to change the CKeditor Code Mirror theme and options.

As you can see, the editor is hard to read with the default theme.

![image](https://cloud.githubusercontent.com/assets/40570/21030125/8f68dfd4-bd62-11e6-80bd-76a6385ef555.png)

Here is my configurations if it helps:
![image](https://cloud.githubusercontent.com/assets/40570/21030162/b86661d6-bd62-11e6-9e87-5989bd2faf41.png)

I also tried creating the cke.js file in /sites/templates/cke.js per https://github.com/rolandtoth/AdminOnSteroids#auto-loaded-files , but it didn't seem to work.

I also tried entering the path /sites/templates/cke.js in the CKEditor custom configuration script input, but still couldn't see any changes.

Here is the contents of that file:
```js
config.extraPlugins = 'sourcedialog,codemirror';
config.codemirror = {

    // Set this to the theme you wish to use (codemirror themes)
    theme: 'default',

    // Whether or not you want to show line numbers
    lineNumbers: true,

    // Whether or not you want to use line wrapping
    lineWrapping: true,

    // Whether or not you want to highlight matching braces
    matchBrackets: true,

    // Whether or not you want tags to automatically close themselves
    autoCloseTags: true,

    // Whether or not you want Brackets to automatically close themselves
    autoCloseBrackets: true,

    // Whether or not to enable search tools, CTRL+F (Find), CTRL+SHIFT+F (Replace), CTRL+SHIFT+R (Replace All), CTRL+G (Find Next), CTRL+SHIFT+G (Find Previous)
    enableSearchTools: true,

    // Whether or not you wish to enable code folding (requires 'lineNumbers' to be set to 'true')
    enableCodeFolding: true,

    // Whether or not to enable code formatting
    enableCodeFormatting: true,

    // Whether or not to automatically format code should be done when the editor is loaded
    autoFormatOnStart: true,

    // Whether or not to automatically format code should be done every time the source view is opened
    autoFormatOnModeChange: true,

    // Whether or not to automatically format code which has just been uncommented
    autoFormatOnUncomment: true,

    // Define the language specific mode 'htmlmixed' for html including (css, xml, javascript), 'application/x-httpd-php' for php mode including html, or 'text/javascript' for using java script only
    mode: 'htmlmixed',

    // Whether or not to show the search Code button on the toolbar
    showSearchButton: true,

    // Whether or not to show Trailing Spaces
    showTrailingSpace: true,

    // Whether or not to highlight all matches of current word/selection
    highlightMatches: true,

    // Whether or not to show the format button on the toolbar
    showFormatButton: true,

    // Whether or not to show the comment button on the toolbar
    showCommentButton: true,

    // Whether or not to show the uncomment button on the toolbar
    showUncommentButton: true,

    // Whether or not to show the showAutoCompleteButton button on the toolbar
    showAutoCompleteButton: true,
    // Whether or not to highlight the currently active line
    styleActiveLine: true
};
```

Am I doing something wrong?  I'm using the latest version of AOS.

**Comment by rolandtoth** [comment]
I can't see those dark texts in the default theme.

I see - there are some CSS values coming from the default PW 'monoo' theme that overrides the text color, I'll try to get rid of them.

The change theme:

1. Go to site/modules/AdminOnSteroids/CKE/sample-cke.js and copy the CKEDITOR.editorConfig section.

2. Go to your cke.js file (by default site/templates/cke.js) and paste there, then modify the theme (or other settings).

**Comment by gmclelland** [comment]
Thank you, that worked.

**Comment by jmartsch** [comment]
In recent ProcessWire versions (I used 3.0.62) you can set a global file for the config which resides at /site/modules/InputfieldCKEditor/config.js. This config file will be automatically loaded by ProcessWire, so you don't need to configure it.

You can also make a config file for specific fields if you add a config file with the name
/site/modules/InputfieldCKEditor/config-{fieldname}.js
