### ISSUE TITLE
Uncommented bd() instance on line 1070

### ISSUE THREAD

**Issue by lesaff** [rolandtoth/AdminOnSteroids#27]
Hi Roland, 

I think you might have missed commenting out line 1070 in AdminOnSteroids.module

https://github.com/rolandtoth/AdminOnSteroids/blob/master/AdminOnSteroids.module#L1070

**Comment by rolandtoth** [comment]
Thanks, I'll remove it in a few days.

**Comment by rolandtoth** [comment]
Removed.
