### ISSUE TITLE
alt + d using Reno focuses search input but doesn't show the input

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#28]
Just noticed when I hit alt+d when using the Reno it focuses the search input but doesn't show the input on the screen.

**Comment by rolandtoth** [comment]
What do you mean on doesn't show the input on screen? What type of header are you using, and is the search hidden by default? (there is a feature to always show the search)

**Comment by rolandtoth** [comment]
I think I got it - happens when you haven't set the search box to be always visible. Try v116, it should be fixed now.
