### ISSUE TITLE
Case toggle button isn't positioned correctly in AdminThemeReno

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#29]
Here is a picture
![edit page about us pwtwig dev 2016-12-29 10-54-17](https://cloud.githubusercontent.com/assets/40570/21549039/55a6be52-cdb5-11e6-8735-b77d587f4cf8.jpg)

This happens with all the Reno theme sets.

It looks fine with AdminThemeDefault.

Hope that helps

**Comment by rolandtoth** [comment]
I can't reproduce but I assume there's another submodule CSS that conflicts. I've tried disabling all but this tweak but still can't see it. Could you check what CSS rule is causing this? There should be "right: 16px" for the element "a.case-toggle", is something overwriting it?
(it's "right: 0" if it's a multilanguage site)

**Comment by gmclelland** [comment]
Hrmmm.... It doesn't look like it is being overridden.  Here is my css

``` css
a.case-toggle {
    position: absolute;
    right: 16px;
    padding: 5px 8px;
}
```

It looks better at right:40px;

FYI..My site is not multilingual.

I inspected the css in a new Google Chrome profile without browser extensions.

I also disabled all of AOS except the Miscellaneous Tweaks.

I tried it on a few different sites.  One of them only has TracyDebugger, Upgrade, and AdminOnSteriods modules.

I also tried each theme set of Reno.  It had the same results.

Everything looks good with the AdminThemeDefault.

I'm using ProcessWire 3.0.45.

Hope that helps

**Comment by rolandtoth** [comment]
Somehow the parent inputfield doesn't get the "position: relative" (I guess). I've added that to the "Title" field in v117, please try.

**Comment by gmclelland** [comment]
That worked.  Thanks again.

**Comment by rolandtoth** [comment]
Great, thanks! The "Tooltips" submodule was setting the "position: relative" so I guess it wasn't enabled for you beforehands.
