### ISSUE TITLE
Default admin theme head not sticking

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#3]
Just wanted to report this...

I think this commit broke the sticky header from working on the default admin theme:
https://github.com/rolandtoth/AdminOnSteroids/commit/0db7c4c7a7c048357d7a4c24dfe5db53f87bbe71

The header no longer sticks.

Here are my html classes:
`<html class="aos  AdminThemeDefault headSticky HoverDropdown moduleModal" lang="en">`

I think it might be because line 2451 in AdminOnSteroids.scss is nested under:

```
html.AdminThemeDefault { line 2433
  body:not(.modal) { line 2435
    &.headSticky:not(.modal) { line 2451
```

I think the sticky styles never apply because it is nested under the body.  The .headSticky class is part of the html element which is above the body element.

Hope that helps..Let me know if you need any more information.

**Comment by rolandtoth** [comment]
Thanks, committed a fix.

**Comment by gmclelland** [comment]
Thank you, that fixed the issue for me.

**Comment by rolandtoth** [comment]
Great, thanks!
