### ISSUE TITLE
AOS Option previews are reversed for RenoTweaks

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#30]
Hi @rolandtoth 

I noticed when I visit the AOS settings page with the AdminThemeReno enabled, the options for RenoTweaks seemed to be reversed.

For instance:
Sticky Header is checked by default.  When I uncheck it, I see the sticky header instantly.
Sticky Sidebar is checked by default.  When I uncheck it, I see the sticky sidebar instantly.
Same for "Always show sidebar items (disable accordion)"
Same for Always show search bar
Same for Place header button next to the main title
Same for Show top nav item on hover instead of click

Inline sidebar items works correctly.

Hope that helps

**Comment by rolandtoth** [comment]
These "live" options only add/remove CSS classes from the "html" tag. For example, checking "Place header button next to main title" adds the "headBtnToTitle" class. Do you see this class added differently as it should? It's working fine here btw, even on a fresh install (before first save on module).

**Comment by gmclelland** [comment]
Strange, now it is working correctly.  I just saved the AOS module settings a few minutes ago.  Maybe that helped.  This is the second time I've noticed this.  Hmmmm....

**Comment by rolandtoth** [comment]
I'll close this and reopen if the issue comes up again.
