### ISSUE TITLE
Filter box shows on top of sidebar in AdminThemeReno

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#31]
Here's another one.
![find processwire pwtwig dev 2016-12-30 15-50-29](https://cloud.githubusercontent.com/assets/40570/21573253/cb984dcc-cea7-11e6-8a26-ecb0a2d534de.jpg)

**Comment by gmclelland** [comment]
It also show on top of the drop down menus

![upgrades processwire pwtwig dev 2016-12-30 15-55-55](https://cloud.githubusercontent.com/assets/40570/21573303/8d0d7536-cea8-11e6-84cf-49bce5d9efc9.jpg)

**Comment by rolandtoth** [comment]
Thanks, I've committed a fix (no version change).

**Comment by gmclelland** [comment]
Thanks, I've confirmed that it works.
