### ISSUE TITLE
Add keyboard shortcut to open the page tree panel

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#32]
I think it would be handy to always be able to open the Page Tree Panel from any page with a keyboard shortcut like Alt + O similar to how AOS has a shortcut to focus the search with Alt + D.

What do you think?

**Comment by rolandtoth** [comment]
Sounds good to me, I'll try.

**Comment by rolandtoth** [comment]
There you go (v120). Works as a toggle hotkey (inside the panel's iframe and also on the main PW page).

The Hotkeys submodule also adds ESC hotkey to close the PW panel.

**Comment by gmclelland** [comment]
Thank you, but I think you meant it to be Alt + o instead of Alt + d ?

Alt + d should focus the search box and Alt + o should toggle the tree open.

**Comment by rolandtoth** [comment]
It should work that way, is it work the other way there?

**Comment by gmclelland** [comment]
It works correctly, it's just the label is incorrect.  Sorry, I was in hurry earlier.

![modules processwire pwtwig dev 2017-01-13 13-42-59](https://cloud.githubusercontent.com/assets/40570/21943320/62d37998-d996-11e6-9a4a-fb3e62cd665c.jpg)

**Comment by gmclelland** [comment]
Also in the README.txt

**Comment by rolandtoth** [comment]
Thanks, I'll change that.

**Comment by rolandtoth** [comment]
This is fixed in the latest version.
