### ISSUE TITLE
"Apply to all" link for field position in templates

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#35]
Another idea...

When adding a new field to a bunch of templates you have to manually edit each select field.

Not sure if it is possible... but after selecting an option it would be nice if a "Apply to all" link appeared next to the select menu where you could apply the same configurations to all the other displayed select options.

- It would only do this if there was more than 1 select menu
- It would only appear when selecting fields that are shared between the other templates displayed

![fields processwire pwtwig dev 2017-01-10 15-05-18](https://cloud.githubusercontent.com/assets/40570/21824900/fd779170-d746-11e6-9ea9-933af2baad00.jpg)

I don't know how useful it would be, but I thought I would throw it out there. 😀

**Comment by rolandtoth** [comment]
I've already thought about this, could come handy sometimes. Here is a quick draft:

![Apply to all](http://rolandtoth.hu/pic/apply-to-all.gif)

I'll create its counterpart too, adding a batch confirm button for removing fields.

**Comment by gmclelland** [comment]
That's exactly what I was thinking?  Looking forward to it.  Thank you

**Comment by rolandtoth** [comment]
Done in v119. I've used an icon instead, let me know if you prefer text instead.

**Comment by gmclelland** [comment]
Looks and works great!  Big time saver

**Comment by gmclelland** [comment]
Text or icon.. in this case I don't have a preference.  I'm just happy you developed it from an idea into a module.  It will only be used by site admins who know what they are doing anyways because they are probably the ones that enabled the module in the first place.
