### ISSUE TITLE
Line showing under the horizontal tabs

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#4]
Here it is with AOS disabled:
![good](https://cloud.githubusercontent.com/assets/40570/18318692/49ebea86-74e8-11e6-9612-fda2d8e6a412.jpg)

Here it is after AOS is enabled:
![bad](https://cloud.githubusercontent.com/assets/40570/18318716/6b85d486-74e8-11e6-86eb-a47a140eac4e.jpg)

Notice the line under the "Content" tab?

Let me know if you need any more information.

**Comment by rolandtoth** [comment]
Actually this was a sideeffect of a workaround for the PrevNextTabs module. I think I could found a soution that is good for both cases, at least here in Chrome, see last commit.

**Comment by gmclelland** [comment]
Thank you, that fixed the issue for me, but I'm also not using the PrevNextTabs module.

**Comment by rolandtoth** [comment]
Thanks! This fix should be in PrevNextTabs module anyways, so it it's not a big deal if that fix doesn't work with it (though it should).
