### ISSUE TITLE
edit template link when editing a page

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#40]
When editing a page under the Settings tab, it would be nice if I could click an "edit" link or button to edit the template that the page is assigned to.

![image](https://cloud.githubusercontent.com/assets/40570/24076448/0601fcc6-0bff-11e7-9dfa-5eb1fc33c847.png)

**Comment by rolandtoth** [comment]
[Upgrade time](https://github.com/rolandtoth/AdminOnSteroids/blob/6eec991aa9d0a8094ac2c44e3c3341c70ac6f9d3/CHANGELOG.md#135-2017-03-19) :)

**Comment by gmclelland** [comment]
Works great!  Thank you

**Comment by adrianbj** [comment]
Just a quick thought on UI/UX consistency. What about making the template name appear on mouseover of the select - this would make it similar to mousing over field labels to see the name and an edit link. Also, I noticed that the template edit links opens in a modal, but the field one loads a new page. Is there a reason these shouldn't be consistent?

**Comment by rolandtoth** [comment]
I've used a tooltip for fields because there was no space where I could add it, but it will be probably replaced with a dropdown menu in the future. That will allow adding more items, and it will be accessible on mobile too (even though I think an admin is not designed for mobile use).

I've used modal here because editing a template has no effect on the page you edit (unless you delete the template). This way you can edit the template without navigating away or needing to jump between tabs. But I'm not against using a new page as a target here too.

**Comment by gmclelland** [comment]
I found an issue where the edit icon doesn't show if the page has only one template available.  If the page has more than one template selectable then the edit icon shows.

BTW... This shortcut is very useful.  I've found myself using it a lot.

**Comment by rolandtoth** [comment]
How do you do it to have only one template available for a page?

**Comment by rolandtoth** [comment]
@gmclelland Please try v1.4.2.

**Comment by gmclelland** [comment]
Hi @rolandtoth, sorry for taking so long to get to this.  I had some tight deadlines.

I just tested the latest version and I'm still seeing a problem.

I had two templates where the only difference was this:
![image](https://cloud.githubusercontent.com/assets/40570/26365959/df97f80e-3fae-11e7-9f95-b23ca9623419.png)

The one that has that box checked will not show the template edit link on those pages.
![edit page third thursday haunt the block mansfieldtexasarts dev 2017-05-23 11-58-21](https://cloud.githubusercontent.com/assets/40570/26366033/2f0ae586-3faf-11e7-90c5-d56d19920cd6.jpg)

The one that has that box unchecked will show the template edit link on those pages.

On both pages, the page is only allowed one template. i.e. You can't change to a different template.

Hope that helps.  Let me know if you need more clarification.

**Comment by rolandtoth** [comment]
Thanks, I got it - the jQuery workaround I applied beforehands used the "Parent" field in the template Settings tab, but checking that checkbox made the "Parent" field go away so the selector used didn't match anything.

**Comment by rolandtoth** [comment]
@gmclelland 
Could you check how it works in latest AOS?

**Comment by gmclelland** [comment]
Just upgraded to the latest AOS, but it doesn't look like it is working.  I tried clearing the browser cache and PW module cache a few times, but it still didn't work.

![no-template-edit-link](https://user-images.githubusercontent.com/40570/27867577-b350d734-615f-11e7-8f8f-400a284c57fc.jpg)

**Comment by rolandtoth** [comment]
Thanks, I see where it fails, will update soon.

If you need a quick fix, replace the contents of AdminOnSteroids.min.js with the content of AdminOnSteroids.js, and in AdminOnSteroids.min.js replace the two lines at about line 869-870:

```javascript
                // workaround for scenario: Don't allow pages to be moved + Don't allow pages to change their template (Advanced tab)
                templateEditSettingsElem = $('body[class*="ProcessPageEdit-template-"] #wrap_Inputfield__pw_page_name').next('li.Inputfield').find('i.fa-cubes').parent().parent().find('.InputfieldContent p');
```

**Comment by rolandtoth** [comment]
It's included in v149.
