### ISSUE TITLE
CKEditor - Plugins

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#42]
Hi @rolandtoth,

I'm not sure how it is done, but It would be cool if you included the ability to right click some text and choose "Link" in the CKEditor.  I can't believe this isn't enabled by default in CKEditor.  I guess it would need to pop up the Processwire Link Dialog instead of the native CKEditor Link Dialog?

The closest I could find is from https://www.drupal.org/project/ckeditor_context_link.  I haven't tried it, but maybe this code would help http://cgit.drupalcode.org/ckeditor_context_link/tree/plugins/ckeditor_context_link/plugin.js?

Another good plugin to add might be http://ckeditor.com/addon/autolink to automatically hyperlink urls when pasted into textareas?

Just some thoughts... No worries, if you don't think it is a good idea.

**Comment by rolandtoth** [comment]
Auto Link plugin is included in AOS. However it works only on paste but not when typing a link, at least that's how I remember.

As for the context link it's rather a CKEditor plugin development question, which I don't plan to add to my toolset :)

**Comment by gmclelland** [comment]
Sorry, I missed Auto Link already being included.

Just to be clear here is screenshot of the feature in TinyMCE:
![tinymce the most advanced wysiwyg html editor 2017-03-31 09-19-20](https://cloud.githubusercontent.com/assets/40570/24554448/3600ac30-15f3-11e7-921d-99005dd1911c.jpg)
If I highlight the word "Accessibility" and right click, I see the "Link" in the contextual menu.  If I click "Link", it would open the link dialog.

Is that the same as what you were thinking when you first read my request?  I just wanted to make sure I explained it well.

**Comment by rolandtoth** [comment]
Yes, that was what I thought of. But still it's a CKEditor plugin development issue imo even if probably not a big one.

**Comment by gmclelland** [comment]
Ok, I understand.  No worries
