### ISSUE TITLE
Loosing superuser permissions after update (v115 -> v141)

### ISSUE THREAD

**Issue by esszett** [rolandtoth/AdminOnSteroids#43]
Today I did a processwire (v3.0.42) internal module update. Previous version was AOS 1.1.5 - after running the updater I left the config page without any changes via [submit]. That process took away my superuser access – leaving a very basic TopMenu (admin default theme) without submenus. I could not reenter the module configuration page.
After a second failed try, (wipeout of all AOS settings, reverting to the prevoius version, update again, submit config)… I found out: disabling the module on the settings-page after updating first -> than submit and reopening the settings-page -> reenable the module-> submit … did the trick.

Anybody can confirm that issue?

**Comment by rolandtoth** [comment]
I'm not sure whether this was AOS, perhaps there were other data that was saved on submit.
