### ISSUE TITLE
addPageListIDs, got multiple times added

### ISSUE THREAD

**Issue by horst-n** [rolandtoth/AdminOnSteroids#45]
Hi @rolandtoth,
in a site where I have customized page tree labels, the AOS adds multiple times the page id.
I changed one [line](https://github.com/rolandtoth/AdminOnSteroids/blob/3725e1df24e473420b77a6f2d3869c2d11b63db7/AdminOnSteroids.module#L1112) in the module to bound it only to the span tag with class label_title.
`$markup = str_replace("<span class='label_title'", "<span class='label_title' data-pid=" . $page->id . ' ', $markup);`

![capture_ 136](https://cloud.githubusercontent.com/assets/4884546/26319501/93878a5e-3f1f-11e7-830b-b3477dd9f0ff.jpg)
![capture_ 137](https://cloud.githubusercontent.com/assets/4884546/26319504/97e88562-3f1f-11e7-8a9c-53bb8ad7e383.jpg)

**Comment by rolandtoth** [comment]
Thanks, replaced that line and let's see how it goes. It was like that beforehands but I can't remember why I removed that :)

**Comment by horst-n** [comment]
Thanks! Only thing what I can imagine is, that in some setups maybe there will be no span with a class "label_title". But thats nothing bad. :)

**Comment by rolandtoth** [comment]
Perhaps checking for label_title first and if not found, do a general str_replace (like it was before? Plus limit the replacement to the first match.

**Comment by horst-n** [comment]
That would be 99.9% perfect, I think! :)
