### ISSUE TITLE
Image size and layout in PageEdit issue

### ISSUE THREAD

**Issue by karltaidev** [rolandtoth/AdminOnSteroids#47]
When there are more than one image fields in one PageEdit page, all the image fields lose to their saved layout and size(set by the size bar at top right hand corner), except the first image field. All the image fields follows the same setting of the first image field. I tried disable the module and the issue gone. I also tried uncheck all options the issue gone too.

**Comment by rolandtoth** [comment]
Sounds strange, and I couldn't reproduce at first try. Could you narrow it down to a submodule?

**Comment by karltaidev** [comment]
I have reproduced it in a fresh installed PW. Unfortunately, I have no free time to narrow it down at the moment. I will do it later.

**Comment by karltaidev** [comment]
After some testing, it seems that the issue is from PW's images field its own, not AOS. Sorry for your time.

**Comment by rolandtoth** [comment]
Good to know, thanks!
