### ISSUE TITLE
z-index issue: order icon is covering the delete button

### ISSUE THREAD

**Issue by lesaff** [rolandtoth/AdminOnSteroids#48]
PW: 3.0.69
AoS version: 1.5.0
Using Reno theme

Delete button/icon on the File fieldtype is covered by the order icon (z-index)

See attached
![aos-z-index-delete](https://user-images.githubusercontent.com/1151181/28941561-cbaf9fc4-786e-11e7-9a78-09a638bbfd17.gif)

**Comment by rolandtoth** [comment]
Thanks, this was reported in the forums too, I'll fix soon.

**Comment by rolandtoth** [comment]
Fixed in v151.
