### ISSUE TITLE
Autosize Textareas not resizing

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#5]
Hi tpr,

I just noticed the AOS Autosize Textareas options doesn't appear to be doing anything.  I'm running the latest version 3.0.33 and the AOS commit if that helps.

I using CKeditor that comes with core Processwire.

Do I need to configure the text area field in a certain way to get this to work?

**Comment by rolandtoth** [comment]
AutosizeTextareas doesn't work with CKEditor. I thought it's in the README but it's missing, I'll update it soon.

You can use the Auto Grow plugin for CKEditor fields:
http://ckeditor.com/addon/autogrow

I'll check if I can add plugins somehow with AOS directly, it would be great not having to configure all manually.

**Comment by rolandtoth** [comment]
Good news: it seems it's easy to add CKEditor plugins from within AOS so additional plugins could be added globally. There are some issues to resolve first but it's promising. I use about 5 CKEditor plugins all the time so this feature would be a great time saver.

**Comment by rolandtoth** [comment]
Here is a preview of the new submodule "CKEaddons":
https://processwire.com/talk/topic/13389-adminonsteroids/?do=findComment&comment=127645

The module won't load AutoGrow if AutosizeTextareas are checked, this will be up to the user to enable this for CKE fields.

**Comment by gmclelland** [comment]
This sounds very useful.  Thanks tpr.  I'll test it when it's ready.

**Comment by gmclelland** [comment]
Just tested v61.  I'm not sure if this is how it is supposed to work, but I had to click into the textarea to make the textarea autosize.  Is that the way it supposed to work, or is the textareas supposed to automatically be resized when the page loads?

**Comment by rolandtoth** [comment]
There's a plugin setting to autoload but apparently it's not loaded there. It's probably the same issue as in case of the LightWire skin, but unfortunately I couldn't reproduce yet.

**Comment by gmclelland** [comment]
I just tested the lastest commit of AOS and it now autosizes the textareas on page load so I don't have to click into the textarea in order for it to initialize.

**Comment by rolandtoth** [comment]
You mean the CKEditor textareas, right? Simple textareas were OK in this regard as I know.

**Comment by gmclelland** [comment]
Yes, I'm referring to the CKEditor textareas.  I like the way autogrow works now.
