### ISSUE TITLE
File field delete button stacked on top of the download button

### ISSUE THREAD

**Issue by lesaff** [rolandtoth/AdminOnSteroids#50]
I am using PW 3.0.74 and AoS 1.5.4

![screen shot 2017-09-06 at 5 57 15 pm](https://user-images.githubusercontent.com/1151181/30134257-e84db89a-932c-11e7-8ffd-1d9e86dff169.png)

**Comment by rolandtoth** [comment]
Thanks for the report. Just pushed version 1.5.5, please try.

**Comment by lesaff** [comment]
That did it, thanks for super quick response. 🥇
