### ISSUE TITLE
Template/edit link is inserted in CKE field too, next to H1

### ISSUE THREAD

**Issue by donatasben** [rolandtoth/AdminOnSteroids#52]
Hi.
Just noticed some unexpected behavior:
I enabled Heading 1 tag to use in my CKEditor and AOS adds a link to edit template/page next to it.
I can see such link is hidden near the page's title at the top, but the css rules don't apply in WYSIWYG textarea. Also everytime I save the page - it always adds a new link, so it stacks on every save.
![screenshot_61](https://user-images.githubusercontent.com/4421344/31055366-89f13cca-a6ca-11e7-8b0d-ce4b11e36821.png)
"Home" is the name of template. And it's a home page page :)

The link url is to edit the page (or I've seen to edit the template before deleting some earlier)
![screenshot_62](https://user-images.githubusercontent.com/4421344/31055382-ad0267b6-a6ca-11e7-8b10-280bb20aa0ba.png)

So I imagine you need a more precise selector to insert this link, to target specifically admin page title, but not H1 in textareas.

**Comment by rolandtoth** [comment]
I couldn't reproduce. If you view the page source, are there multiple "H1" tags there? The module replaces `<h1 id="title">` or `<li class='title'>` but CKEditor contents shouldn't be there in the page source.

Is your "H1" tag added via the Styles dropdown from a script, and does it contain a class/id or something else?

**Comment by donatasben** [comment]
Hi. Yes, there are several `<H1>` tags in source. Maybe it is because I have enabled the "Inline Editor" mode for CKEditor, so it loads all textarea contents already formated into the source. I also use LanguageSupport for multiple languages, if it impacts anything more than being multiple H1 tags out there.

I just tried disabling the "Inline Editor" mode in field settings and the problem goes away. But in my case I prefer to use "Inline" mode...

Some example code in my source:
```
<div class="LanguageSupport" id="langTab_Inputfield_body" data-language="1010"><label for="Inputfield_body" class="LanguageSupportLabel detail">En</label><div id="Inputfield_body_ckeditor" class="InputfieldCKEditorInline InputfieldCKEditorInlineEditor" data-configName="InputfieldCKEditor_body">
<h1>Zouk, Kizomba, Bachata and Salsa lessons in Klaipėda!</span><a href="/admin/setup/template/edit?id=1" class="aos_EditTemplate pw-blank" target="_blank">home<i class="fa fa-pencil"></i></a></h1>
</div><input type="hidden" name="body" id="Inputfield_body" value=":IGNORE:" /></div>
```

I can also see some random unopened `</span>` inside `<h1>` there too..

**Comment by rolandtoth** [comment]
Thanks, I could see it with the inline mode. Please try 1.6.0.

**Comment by donatasben** [comment]
Thank you very much! That solves the issue!
