### ISSUE TITLE
Sticky header doesn't work with AdminThemeUikit

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#54]
I know this may take a while to fix, but I thought I would start writing them down as I noticed them.

I noticed the sticky header doesn't stick when the module is enabled.

**Comment by rolandtoth** [comment]
There is no config setting for a "general" sticky header, only for the Default and the Reno theme.

**Comment by adrianbj** [comment]
I still think it would be a nice option to have, perhaps paired with an option to reduce the top and bottom padding so it takes up less space?

**Comment by rolandtoth** [comment]
Certainly, but let's wait some time, perhaps there will be official mods to the theme.

**Comment by adrianbj** [comment]
> Certainly, but let's wait some time, perhaps there will be official mods to the theme.

Yeah, for sure, it's certainly not a big deal.

**Comment by gmclelland** [comment]
This is fixed now.

**Comment by adrianbj** [comment]
> This is fixed now.

Doesn't seem to be working here. Are you viewing in regular layout, or with sidebars? I don't have a sticky header here with regular layout, and of course it is with sidebars because of all the iframes :)

**Comment by gmclelland** [comment]
Oops, sorry I closed the wrong issue.  Reopening..

**Comment by rolandtoth** [comment]
It seems easy to add, but there is an UIkit error (bug?) and also typo in their docs (showup vs showOnUp). 

`
var $uikitMasthead = $('#pw-mastheads');
$('#main').css('padding-top', $uikitMasthead.outerHeight() + 'px');
UIkit.sticky($uikitMasthead, {media: 640, top: 0, getWidthFrom:'#main', showOnUp: false});
`

Will give it another try later, and if no luck, I'll add it with CSS only.

**Comment by adrianbj** [comment]
Thank you for adding this - this is great to have again!

**Comment by rolandtoth** [comment]
Yep, I added this with CSS as I haven't got the patience to find out why things don't work as expected/documented.
