### ISSUE TITLE
Disable/Enable AdminOnSteroids link isn't aligned

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#58]
Here is a screenshot:
![pages processwire pwoliver test 2017-10-02 09-20-46](https://user-images.githubusercontent.com/40570/31081956-1da27f1e-a753-11e7-8712-8078c47ccd2e.jpg)

**Comment by rolandtoth** [comment]
fixed in v1.6.1

**Comment by gmclelland** [comment]
That worked.
