### ISSUE TITLE
v61 ckeditor lightwire skin not working

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#6]
Just tested v61.  If I switch to the ckeditor lightwire skin nothing seems to change.  I have refreshed the page many times to try to clear the cache, but I also don't think I see it including the needed .css

Your doing a great job with all the updates!

**Comment by rolandtoth** [comment]
Are you sure you don't have a custom config.js loaded? That would override settings in AOS.

What browser are you using?

**Comment by rolandtoth** [comment]
Plus which admin theme are you using?

**Comment by rolandtoth** [comment]
I may found the issue: try placing an empty config.js file here:

`/site/modules/InputfieldCKEditor/config.js`

Unfortunately I see no way to tell PW to load this file from the AdminOnSteroids module's directory so this will probably need to be done manually if works.

Actually you can place anything into it but do not override 'CKEDITOR.editorConfig' stuff, unless you know what you're doing.

**Comment by rolandtoth** [comment]
Nevermind, I switched to custom config.js for each CKEditor wich can be located under AOS dir and this seems to fix the issue here. Download the module again from GitHub to check, no need to use the workaround I wrote above.

**Comment by gmclelland** [comment]
Just tested the latest and it is working now.
