### ISSUE TITLE
AdminThemeUikit - Page list actions hover on full row not working.

### ISSUE THREAD

**Issue by adrianbj** [rolandtoth/AdminOnSteroids#64]
I know I posted in the forum about this, but in an effort to help you keep track, here's a reminder :)

Thanks!

**Comment by rolandtoth** [comment]
I may have overlooked it but your original request was to support that in the sidebar panel, which is working in the Default theme. In Reno it was supported out of the box if I remember well.

Currently there is no "AdminThemeUikit tweaks" in aos, so how could it work? :)

**Comment by adrianbj** [comment]
Not expecting it to magically work - sorry, I guess this shouldn't be an "Issue", but rather a "Feature Request". 

I know you are probably wondering how you are going to support all your brilliant tweaks across multiple themes. I am assuming that AdminThemeUikit will become the default theme sometime soon, but I guess at this stage we don't know anything for certain.

Anyway, please keep up the amazing work, but certainly don't feel pressured by any of these "Issues" :)

**Comment by rolandtoth** [comment]
Added to v163 (find under PageListTweaks).

**Comment by adrianbj** [comment]
Thank you - really great to have this back!
