### ISSUE TITLE
Frontend In Place CKEditor Configs

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#7]
I noticed the new configs for CKEditor work on the backend but not the frontend in place editor.

Is there a way to control the frontend in place CKeditor as well?

**Comment by gmclelland** [comment]
I hope I'm not wearing you out with all these issue reportings.

**Comment by rolandtoth** [comment]
No, AOS is strictly loaded only in the admin:

`'autoload'  => 'template=admin'`

**Comment by rolandtoth** [comment]
I close this because AOS is restricted to the admin area only.
