### ISSUE TITLE
Margin issue when sticky header is disabled

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#74]
I noticed when view the Classic default theme and the sticky header is disabled, the page sits to close to the top bar.

![modules processwire pwoliver test 2017-10-25 17-11-07](https://user-images.githubusercontent.com/40570/32025910-8da70d28-b9a7-11e7-9681-7fd120a98b18.jpg)

When the sticky header is enabled, everything looks okay.

**Comment by adrianbj** [comment]
I don't think that is actually the fault of AOS - I think it is the Module Settings Import / Export module, or maybe it's actually a PW core issue when adding a new fieldset before others on the module settings pages. If you disable AOS you'll see it's still a problem.

**Comment by gmclelland** [comment]
Hmm.. On a different site with an older version of AOS it works properly.

I also tried unistalling the Module Settings Import / Export module, but it made no difference.

> If you disable AOS you'll see it's still a problem.

Your right I do see this when the module is disabled.

**Comment by rolandtoth** [comment]
As I remember there was a fix for this in AOS, perhaps it got removed lately (by accident). I can confirm that it's like this by default.

**Comment by gmclelland** [comment]
The site that works correctly is using AOS 1.5.7

**Comment by rolandtoth** [comment]
I guess I was wrong, I though about the current fix that is present in case sticky header is enabled, so there was no fix for the non-sticky header case. I've fixed it, will update the module soon.

**Comment by rolandtoth** [comment]
Should be fixed in v163.
