### ISSUE TITLE
 Disable AdminOnSteroids link not aligned

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#79]
Hi @rolandtoth,

Just installed the latest and noticed the Disable AdminOnSteroids link at the bottom of the page isn't correctly aligned when using the PW core AdminThemeUikit. 

This only happens when the screen is wide.  When the screen gets smaller, it hits a breakpoint and the link is correctly aligned.

![modules](https://user-images.githubusercontent.com/40570/33436623-3343cc5c-d5ab-11e7-8b99-eb76d3769334.jpg)

**Comment by rolandtoth** [comment]
This was fixed in the latest release, thanks!

**Comment by gmclelland** [comment]
Many thanks!  Just tested, it is fixed now.

**Comment by adrianbj** [comment]
@rolandtoth - for me at least, it looks fine with it is enabled, but when it's disabled, it's still in the wrong spot.

**Comment by gmclelland** [comment]
Ya, I just noticed that as well.

**Comment by rolandtoth** [comment]
Thanks, got it fixed. The variable holding the admin theme name wasn't set when AOS was disabled. Getting it with wire('config')->defaultAdminTheme fixed that.

**Comment by gmclelland** [comment]
👍 - great job @rolandtoth
