### ISSUE TITLE
Disable Filename Truncation does not work when field is required

### ISSUE THREAD

**Issue by gingebaker** [rolandtoth/AdminOnSteroids#84]
Hi

Found one issue with the FileFieldTweak "Disable Filename Truncation"

If the file field for example is required it will not add the noShortName = 1. This is because you are using the $event->object->class for checking. This variable will have the value "FieldtypeFile required", wich will not pass the if statement.

You could change the if statement here:
https://github.com/rolandtoth/AdminOnSteroids/blob/master/AdminOnSteroids.module#L1384
to:

```php
if ($event->object instanceof FieldtypeFile) {
   return;
}
```
Thx for this great module!

**Comment by rolandtoth** [comment]
This is a much better check, thanks! Will be included in the next update.
