### ISSUE TITLE
Unselect/restore buttons in AdminThemeUikit

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#86]
A small layout issue with the unselect/restore buttons for InputfieldPageListSelect in AdminThemeUikit.

![2018-01-18_115536](https://user-images.githubusercontent.com/1538852/35071830-0df9cd3a-fc47-11e7-945f-0b3eb6166f0b.png)

**Comment by rolandtoth** [comment]
Thanks, should be fixed in v1.7.4

**Comment by Toutouwai** [comment]
Thanks!
