### ISSUE TITLE
Search filter doesn't work on some pages

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#87]
Typing in the input field doesn't do anything on the following pages
- /processwire/access/users/ - try typing "guest"
- /processwire/page/lister/

Note: I do have Profields: Lister.  Maybe thats the problem?

No errors displayed in the console.  I also noticed the font color in the input field's placeholder text is off.  It looks like the Classic theme instead of the AdminThemeUikit's colors.

![filter](https://user-images.githubusercontent.com/40570/35158148-da293a94-fcfb-11e7-94ef-e1a93a879c63.jpg)

Hope that helps

**Comment by rolandtoth** [comment]
Users page: "guest" is most likely to be present in all rows :)
(that's the default role that everyone gets. Does it work if you search for something else?)

I see the bug on the Find (lister) page, I'll check.

**Comment by gmclelland** [comment]
It looks like it works fine for users other than "guest".

**Comment by rolandtoth** [comment]
This should be fixed in v1.7.5.

**Comment by gmclelland** [comment]
Thanks @rolandtoth !  I tested it and it works now.
