### ISSUE TITLE
Image and File field filterbox styling is off on adminThemeUikit

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#88]
![filter](https://user-images.githubusercontent.com/40570/35356590-7b1e37ce-0116-11e8-981d-0c1b66edd92e.jpg)

See how the input touches the label?

**Comment by rolandtoth** [comment]
Thanks, should be fixed in v1.7.6.

**Comment by gmclelland** [comment]
Much better.  Thanks as always!
