### ISSUE TITLE
Z-index issue with sticky header

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#91]
Hi tpr,

I came across some z-index issues with the latest version of AOS.

Here's a pic:
![stickyheader](https://user-images.githubusercontent.com/40570/38769070-9e468cfc-3fc2-11e8-92ca-dbcea3ff880d.jpg)

You can see the issue when scrolling the page.

**Comment by rolandtoth** [comment]
I'll check, thanks. Perhaps I should support only the uikit theme to spot such issues but personally I'm not convinced that it's more effective then the reno theme (it's too big!).

**Comment by rolandtoth** [comment]
Could you re-check? I do not see it with the current latest AOS/PW.

**Comment by gmclelland** [comment]
Yes, it seems to be fixed now.  I upgraded AOS and Processwire from 3.0.103 to 3.0.105
