### ISSUE TITLE
Minor Page List Select spacing issue on AdminThemeUikit

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#92]
Occurs when the Page List Select has no page selected.

Without AOS:
![2018-05-05_131442](https://user-images.githubusercontent.com/1538852/39658316-7302eefa-5066-11e8-8248-a936ee2a4878.png)

With AOS:
![2018-05-05_131430](https://user-images.githubusercontent.com/1538852/39658322-808f5338-5066-11e8-9120-04cb36a88075.png)

**Comment by rolandtoth** [comment]
Thanks, seems like a clearfix has enough to solve. Will be available in 1.9.3.

**Comment by rolandtoth** [comment]
I cannot seem to reproduce, just tried it on another PW install (latest 101 dev) and with AOS enabled pagelist unselect tweak only (to make sure nothing interferes). Do you have something checked in Uikit field settings by any chance? But if you can confirm the clearfix you mentioned fixes it, I'll add that.

**Comment by Toutouwai** [comment]
I think I see where the confusion is coming from.

You must be looking at InputfieldPageListSelect when it is used as the inputfield for a Page Reference field, whereas I am looking at cases when InputfieldPageListSelect is used directly, e.g. in a Process module. In these cases the wrapping element is different.

If you apply the clearfix to both of the following it will cover both scenarios:
`.InputfieldPageListSelect`
`.InputfieldPageListSelect .InputfieldContent`

Thanks.

**Comment by rolandtoth** [comment]
Thanks, just committed this update (no version change).

**Comment by Toutouwai** [comment]
Thanks.
