### ISSUE TITLE
Error if $_SERVER['HTTP_REFERER'] not present

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#93]
In some situations `$_SERVER['HTTP_REFERER']` may not be present (e.g. referrer is disabled), which causes a PHP notice and failed redirect.

Suggest a change [here](https://github.com/rolandtoth/AdminOnSteroids/blob/5ab762a0ab2216a7ae6e786bb2c310cc43a65644/AdminOnSteroids.module#L367-L369):
```php
if(isset($_SERVER['HTTP_REFERER'])) {
    $this->session->redirect($_SERVER['HTTP_REFERER']);
    $this->halt();
}
```

**Comment by rolandtoth** [comment]
Thanks, I will include in 1.9.4.

**Comment by Toutouwai** [comment]
Thanks for the update.
