### ISSUE TITLE
1 pixel misalignment of title field in AdminThemeUikit

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#94]
AOS causes a 1 pixel misalignment of the title field in AdminThemeUikit. It becomes noticeable when the width of the title field is not 100% (i.e. it has a neighbouring inputfield on the same row).

![2018-05-18_145438](https://user-images.githubusercontent.com/1538852/40213829-a382be9e-5aab-11e8-8e51-0ca5786fca20.png)

The title field is 1 pixel taller than it should be. And although it's not noticeable in the screenshot above (and hardly matters) it's also 1 pixel wider than it should be.

The issue seems to be related to the `position: relative` that is added to both the `.Inputfield` element and the `.InputfieldContent` element. I think those styles are added to support the case toggle button, but the styles are actually added regardless of whether that option is enabled in AOS.

Not sure of a good solution. Perhaps the case toggle option could also add a containing div around the button and then the button could be positioned relative to that div rather than changing the position property of `.Inputfield` and `.InputfieldContent`?

**Comment by rolandtoth** [comment]
I've removed `position: relative` (also from the inputfield wrapper) and fixed this with some CSS trickery. Looks OK in all 3 admin themes here.

**Comment by Toutouwai** [comment]
Thanks.

Looks like `position: relative` is going to be a headache with inputfields in AdminThemeUikit: https://github.com/processwire/processwire-issues/issues/602#issuecomment-391322517
