### ISSUE TITLE
Save hotkey issue with HTML required attribute

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#95]
When the HTML required attribute is set for a required inputfield...

![2018-06-03_111805](https://user-images.githubusercontent.com/1538852/40881641-0d953f66-6720-11e8-990c-3752940654a9.png)

...the AOS save hotkey applies the locking overlay before the form is successfully submitted...

![2018-06-03_111706](https://user-images.githubusercontent.com/1538852/40881653-2948ae64-6720-11e8-8876-620abfb6a645.png)

Maybe a change could be made to apply the overlay only after the form is submitted.

**Comment by rolandtoth** [comment]
Thanks, I have fixed this. However, there's an error if you are on another tab (eg. on the Settings on your screenshot) and try to save:

```javascript
An invalid form control with name='excerpt' is not focusable.
```

This is coming from ProcessWire as it happens also if you disable AOS or simply try to click on the Save button.

**Comment by Toutouwai** [comment]
Thanks for the fix.

The error notice that happens when a required field is not visible is a tricky one. You're right that it would be good to avoid that problem - the best thing would be to switch to the tab with the empty required field. An alert would be better than the status quo too. Trouble is I don't know if there is any way to intercept the browser's HTML5 validation with Javascript before it happens. Will do some investigating.
