### ISSUE TITLE
Field edit link added twice for radios inputfield

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#96]
On a Page Reference field using a radios inputfield, the field edit link seems to be added twice. This causes a gap between the inputfield header and content.

![2018-06-05_130824](https://user-images.githubusercontent.com/1538852/40949400-0ee011e0-68c2-11e8-9329-7129e5cf2b12.png)

![2018-06-05_130945](https://user-images.githubusercontent.com/1538852/40949404-120da210-68c2-11e8-8a0d-8d58296ecc16.png)

**Comment by rolandtoth** [comment]
I've fixed it without further examining the root cause (with a simple strpos if). 

The spacing issue was not caused by this but by the uikit css rule `*+ul { margin-top: 20px; }`. Appending the edit link instead prepending fixed this.

**Comment by Toutouwai** [comment]
Great, thanks!

> I've fixed it without further examining the root cause

I think the cause is that Page Reference fields are a combination of two inputfields: InputfieldPage and whatever inputfield type is selected in the field settings, meaning the method gets called twice for Page Reference fields. So alternatively you could exclude InputfieldPage, but the way you've fixed it is good because that would cover it in case there are any other fields that render more than one inputfield.

**Comment by rolandtoth** [comment]
Ok, thanks for the explanation. I was thinking something like that but I was lazy to dig deeper.
