### ISSUE TITLE
z-index issue after page moved in Page List

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#97]
After a page has been sorted/moved it is stacked above the main menu dropdowns.

![2018-07-01_140109](https://user-images.githubusercontent.com/1538852/42130377-848bf83a-7d37-11e8-94ce-345a3eae9105.png)

**Comment by rolandtoth** [comment]
Thanks, added a workaround for this in v1.9.8. An inline CSS is remaining on the pagelist item after moving with a high z-index value, which is imo not required at all.

**Comment by Toutouwai** [comment]
Thanks for the fix.
