### ISSUE TITLE
Field edit link for repeaters points to wrong field

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#98]
The field edit link for Repeater fields links not to the Repeater field settings as expected, but to the first child field in the repeater item template.

So in the screenshot below the field edit link for repeater_2 points to text_1.

![2018-07-06_115337](https://user-images.githubusercontent.com/1538852/42353259-88840092-8113-11e8-9171-4d814db12a67.png)

**Comment by rolandtoth** [comment]
Please try v1.9.9

**Comment by Toutouwai** [comment]
Working great, thanks.
