### ISSUE TITLE
Layout issue when notes field follows PageListSelect

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#99]
The screenshot below is from the settings of a PageTable field.

![2018-07-13_095921](https://user-images.githubusercontent.com/1538852/42662000-0420a44c-8684-11e8-871c-5fb4a815047f.png)

**Comment by rolandtoth** [comment]
Please try v1.9.9

**Comment by Toutouwai** [comment]
Thanks!
